### ISSUE TITLE
Lambda layer support for Python 3.9

### ISSUE THREAD

**Issue by ericksoen** [aws-observability/aws-otel-lambda#222]
**Is your feature request related to a problem? Please describe.**
We have Lambda functions that we'd like to upgrade to use Python 3.9. When we test the upgrade path and use the Lambda layer that targets Python 3.8, the Lambda layer returns the following error:

```bash
ChannelCredentials, Compression
File "/opt/python/grpc/__init__.py", line 22, in <module>
from grpc import _compression
File "/opt/python/grpc/_compression.py", line 15, in <module>
from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)
Failed to auto initialize opentelemetry
Traceback (most recent call last):
File "/opt/python/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 116, in initialize
_load_configurators()
File "/opt/python/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 109, in _load_configurators
raise exc
File "/opt/python/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 105, in _load_configurators
entry_point.load()().configure(auto_instrumentation_version=__version__)  # type: ignore
File "/var/task/opentelemetry/sdk/_configuration/__init__.py", line 178, in configure
self._configure(**kwargs)
File "/var/task/opentelemetry/sdk/_configuration/__init__.py", line 194, in _configure
_initialize_components(kwargs.get("auto_instrumentation_version"))
File "/var/task/opentelemetry/sdk/_configuration/__init__.py", line 148, in _initialize_components
trace_exporters = _import_exporters(exporter_names)
File "/var/task/opentelemetry/sdk/_configuration/__init__.py", line 122, in _import_exporters
) in _import_tracer_provider_config_components(
File "/var/task/opentelemetry/sdk/_configuration/__init__.py", line 108, in _import_tracer_provider_config_components
component_impl = entry_point.load()
File "/var/task/pkg_resources/__init__.py", line 2465, in load
return self.resolve()
File "/var/task/pkg_resources/__init__.py", line 2471, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/opt/python/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 20, in <module>
from grpc import ChannelCredentials, Compression
File "/opt/python/grpc/__init__.py", line 22, in <module>
from grpc import _compression
File "/opt/python/grpc/_compression.py", line 15, in <module>
from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)
[ERROR]	2022-02-09T14:57:20.701Z	9003dd25-68a1-4070-90ee-203e3b98a61b	TracerProvider was missing `force_flush` method. This is necessary in case of a Lambda freeze and would exist in the OTel SDK implementation.
```

**Describe the solution you'd like**
Add OTEL Lambda Layer support for Python 3.9

**Describe alternatives you've considered**
Pause migration to Python 3.9 for Lambda functions that implement OpenTelemetry layer.

**Comment by wangzlei** [comment]
[aws-otel-python38](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python) layers contain c extension files so it is not version compatible with python 3.9. We are actively supporting Lambda 3.9 runtime by providing a new group of layer `aws-otel-python39`. 
Before it is done, a workaround is you can build aws-otel layer from scratch in your own account. Please refer the steps in  [github workflow](https://github.com/aws-observability/aws-otel-lambda/blob/main/.github/workflows/main-build.yml).

**Comment by ericksoen** [comment]
We'll probably wait for the officially supported Python 3.9 runtime for Lambda, but the extra info on building our own layer is an interesting technique to keep in the background.

**Comment by wangzlei** [comment]
Reopen this issue for tracking python 3.9 support. @vasireddy99

**Comment by TriQuach** [comment]
We're experiencing the same issue. Just wondering if the issue has been fixed or do we have a tentative date that it can be fixed?

**Comment by vasireddy99** [comment]
HI @TriQuach, the support for `Python3.9` has be implemented and will be available in next Lambda Layer release, they are expected to be out by May 16th. I shall provide more info here, if there are any more updates.

**Comment by vasireddy99** [comment]
Update : The Lambda layer for Python3.9 is now [available](https://github.com/aws-observability/aws-otel-lambda#aws-managed-opentelemetry-lambda-layers)
