### ISSUE TITLE
Cannot redefine property: handler

### ISSUE THREAD

**Issue by revmischa** [aws-observability/aws-otel-lambda#284]
**Describe the bug**
```ts
      scope.addDefaultFunctionEnv({
        [EnvVars.openTelemetryEnabled]: "true",
        AWS_LAMBDA_EXEC_WRAPPER: "/opt/otel-handler",
      })
      const otelLayer = LayerVersion.fromLayerVersionArn(
        this,
        "OpenTelemetryLayer",
        `arn:aws:lambda:${scope.region}:901920570463:layer:aws-otel-nodejs-amd64-ver-1-5-0:2`
      )
      scope.addDefaultFunctionLayers([otelLayer])
```

handler:
```
export const handler = async (): Promise<string> => {
...
}
```

```
 ❌  mish-platform-DbMigrations failed: Received response status [FAILED] from custom resource. Message returned: Cannot redefine property: handler

Logs: /aws/lambda/mish-platform-DbMigration-MigrationScriptMigration-hWdyvtv7f92D

    at Function.defineProperty (<anonymous>)
    at defineProperty (/opt/nodejs/node_modules/shimmer/index.js:14:10)
    at AwsLambdaInstrumentation.wrap [as _wrap] (/opt/nodejs/node_modules/shimmer/index.js:56:3)
    at InstrumentationNodeModuleFile.patch (/opt/nodejs/node_modules/@opentelemetry/instrumentation-aws-lambda/src/instrumentation.ts:124:20)
    at AwsLambdaInstrumentation._onRequire (/opt/nodejs/node_modules/@opentelemetry/instrumentation-aws-lambda/node_modules/@opentelemetry/instrumentation/src/platform/node/instrumentation.ts:126:23)
    at null.<anonymous> (/opt/nodejs/node_modules/@opentelemetry/instrumentation-aws-lambda/node_modules/@opentelemetry/instrumentation/src/platform/node/instrumentation.ts:161:25)
    at Module.Hook._require.Module.require (/opt/nodejs/node_modules/require-in-the-middle/index.js:175:32)
    at Module.Hook._require.Module.require (/opt/nodejs/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/opt/nodejs/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/opt/nodejs/node_modules/require-in-the-middle/index.js:101:39) (RequestId: 582b69af-9ad1-4ffd-b0de-d8f9c32b24db)
```

**Additional context**
Node 16, Serverless Stack

**Comment by vasireddy99** [comment]
Can you please add more detail in the issue? Such as what is expected and what did you see instead.

**Comment by revmischa** [comment]
I was hoping to instrument my application. I want to use https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing to gather data about what queries my serverless application is performing and have the results appear in xray.

**Comment by revmischa** [comment]
Still an issue for me

**Comment by Dutzu** [comment]
Tried it today, the issue is still there...

**Comment by thiskevinwang** [comment]
I think the root cause might be this CJS vs. ESM issue noted here
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1287

**Comment by pyrae-alex** [comment]
Using CJS vs ESM style exports fixed this issue for me.

E.g
```javascript
export const handler = function() {}
```
refactored to
```javascript
const handler = function() {}
module.exports = { handler }
```

**Comment by magistersart** [comment]
I'm having the same issue, but strictly bound to ESM

**Comment by MatthewWalkerSky** [comment]
I am also having this issue

**Comment by my-kanzari** [comment]
I also having the same issue and refactoring everything according to https://github.com/aws-observability/aws-otel-lambda/issues/284#issuecomment-2239544916 doesn't seem like an option
